// Generated by AshTypescript - RPC Actions
// Do not edit this file manually

import { Channel } from "phoenix";

import type { AshRpcError } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}


/**
 * Configuration options for action channel RPC requests
 */
export interface ActionChannelConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: ReadonlyArray<string | Record<string, any>>;
  filter?: Record<string, any>;
  sort?: string | string[];
  page?:
    | {
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // Channel-specific
  channel: any; // Phoenix Channel
  resultHandler: (result: any) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;

  // Multitenancy
  tenant?: string;

  // Hook context
  hookCtx?: Record<string, any>;
}



/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}




/**
 * Internal helper function for making action channel push requests
 * Handles hooks and channel push with receive handlers
 * @param config Configuration matching ActionChannelConfig
 */
export async function executeActionChannelPush<T>(
  channel: any,
  payload: Record<string, any>,
  timeout: number | undefined,
  config: ActionChannelConfig
) {
    const processedConfig = config;

  const effectiveTimeout = timeout;

  channel
    .push("run", payload, effectiveTimeout)
    .receive("ok", async (result: T) => {

      config.resultHandler(result);
    })
    .receive("error", async (error: any) => {

      (config.errorHandler
        ? config.errorHandler
        : (error: any) => {
            console.error(
              `An error occurred while running action ${payload.action}:`,
              error
            );
          })(error);
    })
    .receive("timeout", async () => {

      (config.timeoutHandler
        ? config.timeoutHandler
        : () => {
            console.error(`Timeout occurred while running action ${payload.action}`);
          })();
    });
}





export type InferCockpitTodayResult = Record<string, any>;

export type CockpitTodayResult = | { success: true; data: InferCockpitTodayResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Cockpit
 *
 * @ashActionType :action
 */
export async function cockpitToday(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CockpitTodayResult> {
  const payload = {
    action: "cockpit_today",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeActionRpcRequest<CockpitTodayResult>(
    payload,
    config
  );
}


/**
 * Execute generic action on Cockpit
 *
 * @ashActionType :action
 */
export async function cockpitTodayChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: CockpitTodayResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<CockpitTodayResult>(
    config.channel,
    {
    action: "cockpit_today",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


export type IcmPageInput = {
  path: string;
};

export type InferIcmPageResult = Record<string, any>;

export type IcmPageResult = | { success: true; data: InferIcmPageResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on ICM
 *
 * @ashActionType :action
 */
export async function icmPage(
  config: {
  tenant?: string;
  input: IcmPageInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<IcmPageResult> {
  const payload = {
    action: "icm_page",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<IcmPageResult>(
    payload,
    config
  );
}


/**
 * Execute generic action on ICM
 *
 * @ashActionType :action
 */
export async function icmPageChannel(config: {
  channel: Channel;
  tenant?: string;
  input: IcmPageInput;
  resultHandler: (result: IcmPageResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<IcmPageResult>(
    config.channel,
    {
    action: "icm_page",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


export type InferIcmTreeResult = Record<string, any>;

export type IcmTreeResult = | { success: true; data: InferIcmTreeResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on ICM
 *
 * @ashActionType :action
 */
export async function icmTree(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<IcmTreeResult> {
  const payload = {
    action: "icm_tree",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeActionRpcRequest<IcmTreeResult>(
    payload,
    config
  );
}


/**
 * Execute generic action on ICM
 *
 * @ashActionType :action
 */
export async function icmTreeChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: IcmTreeResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<IcmTreeResult>(
    config.channel,
    {
    action: "icm_tree",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


export type InferCloseWorkspaceResult = Record<string, any>;

export type CloseWorkspaceResult = | { success: true; data: InferCloseWorkspaceResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function closeWorkspace(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CloseWorkspaceResult> {
  const payload = {
    action: "close_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeActionRpcRequest<CloseWorkspaceResult>(
    payload,
    config
  );
}


/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function closeWorkspaceChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: CloseWorkspaceResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<CloseWorkspaceResult>(
    config.channel,
    {
    action: "close_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


export type CreateWorkspaceInput = {
  parentDir: string;
  name: string;
};

export type InferCreateWorkspaceResult = Record<string, any>;

export type CreateWorkspaceResult = | { success: true; data: InferCreateWorkspaceResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function createWorkspace(
  config: {
  tenant?: string;
  input: CreateWorkspaceInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateWorkspaceResult> {
  const payload = {
    action: "create_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<CreateWorkspaceResult>(
    payload,
    config
  );
}


/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function createWorkspaceChannel(config: {
  channel: Channel;
  tenant?: string;
  input: CreateWorkspaceInput;
  resultHandler: (result: CreateWorkspaceResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<CreateWorkspaceResult>(
    config.channel,
    {
    action: "create_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


export type InferGetWorkspaceResult = Record<string, any>;

export type GetWorkspaceResult = | { success: true; data: InferGetWorkspaceResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function getWorkspace(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetWorkspaceResult> {
  const payload = {
    action: "get_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeActionRpcRequest<GetWorkspaceResult>(
    payload,
    config
  );
}


/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function getWorkspaceChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: GetWorkspaceResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<GetWorkspaceResult>(
    config.channel,
    {
    action: "get_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


export type InspectWorkspaceInput = {
  path: string;
};

export type InferInspectWorkspaceResult = Record<string, any>;

export type InspectWorkspaceResult = | { success: true; data: InferInspectWorkspaceResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function inspectWorkspace(
  config: {
  tenant?: string;
  input: InspectWorkspaceInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<InspectWorkspaceResult> {
  const payload = {
    action: "inspect_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<InspectWorkspaceResult>(
    payload,
    config
  );
}


/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function inspectWorkspaceChannel(config: {
  channel: Channel;
  tenant?: string;
  input: InspectWorkspaceInput;
  resultHandler: (result: InspectWorkspaceResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<InspectWorkspaceResult>(
    config.channel,
    {
    action: "inspect_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


export type OpenWorkspaceInput = {
  path: string;
};

export type InferOpenWorkspaceResult = Record<string, any>;

export type OpenWorkspaceResult = | { success: true; data: InferOpenWorkspaceResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function openWorkspace(
  config: {
  tenant?: string;
  input: OpenWorkspaceInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<OpenWorkspaceResult> {
  const payload = {
    action: "open_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<OpenWorkspaceResult>(
    payload,
    config
  );
}


/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function openWorkspaceChannel(config: {
  channel: Channel;
  tenant?: string;
  input: OpenWorkspaceInput;
  resultHandler: (result: OpenWorkspaceResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<OpenWorkspaceResult>(
    config.channel,
    {
    action: "open_workspace",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


export type InferRecentWorkspacesResult = Array<Record<string, any>>;

export type RecentWorkspacesResult = | { success: true; data: InferRecentWorkspacesResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function recentWorkspaces(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RecentWorkspacesResult> {
  const payload = {
    action: "recent_workspaces",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeActionRpcRequest<RecentWorkspacesResult>(
    payload,
    config
  );
}


/**
 * Execute generic action on Workspace
 *
 * @ashActionType :action
 */
export async function recentWorkspacesChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: RecentWorkspacesResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<RecentWorkspacesResult>(
    config.channel,
    {
    action: "recent_workspaces",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}

