defmodule Valea.Mounts.MountsMd do
  @moduledoc """
  Generates `<workspace>/MOUNTS.md` — the agent-readable index that routes
  a Claude Code session (Valea-run OR bare) to each enabled mount's own
  `AGENTS.md`, from the current mount set (`Valea.Mounts.list/1`).

  Regenerated wholesale, never hand-edited: `regenerate/1` reads the full
  mount set fresh every time and overwrites the file atomically (tmp
  sibling + `File.rename!`, mirroring `Valea.Mounts.Manifest.write!/2`).
  Callers — scaffold, migration, mount enable/disable, and the
  `{:mounts_changed}` PubSub consumer — are wired up in later tasks; this
  module only builds the file.

  Every discovered mount lands in exactly one of three sections, split the
  same way `Valea.Mounts`'s own `effective?/1` does:

    * **enabled** (`degraded: nil`, `enabled: true`) — a `### <name>` block
      with the manifest's description, workspace-relative path, and an
      `@mounts/<name>/AGENTS.md` file-reference line (the same `@`-prefixed
      convention the workspace root `AGENTS.md` already uses) so an agent
      reading this file is routed straight into the mount's own
      instructions.
    * **deactivated** (`degraded: nil`, `enabled: false`) — listed by name,
      no `@`-ref: the mount's `AGENTS.md` is intentionally NOT pulled in
      while it's turned off.
    * **degraded** (`degraded: reason`) — listed with its reason, no
      `@`-ref. A degraded mount's `manifest` may be `nil` (missing or
      invalid `icm.yaml`), so this section renders from `mount.name` (the
      directory basename) only and never touches `mount.manifest`.

  An empty section (e.g. no disabled mounts) is omitted entirely rather
  than rendered with a "none" placeholder.
  """

  alias Valea.Mounts

  @header """
  <!-- Generated by Valea. Do not edit by hand — this file is regenerated \
  automatically whenever mounts change. -->

  # Mounts

  This workspace is composed of one or more mounts under `mounts/`. Each \
  enabled mount below is a self-contained module — read its own AGENTS.md \
  before working inside it.\
  """

  @doc "Regenerates `<workspace>/MOUNTS.md` from the current mount set. Always overwrites."
  @spec regenerate(workspace :: String.t()) :: :ok
  def regenerate(workspace) when is_binary(workspace) do
    content =
      workspace
      |> Mounts.list()
      |> render()

    atomic_write!(Path.join(workspace, "MOUNTS.md"), content)

    :ok
  end

  # -- rendering -----------------------------------------------------------

  defp render(mounts) do
    {enabled, deactivated, degraded} = categorize(mounts)

    [
      @header,
      enabled_section(enabled),
      deactivated_section(deactivated),
      needs_attention_section(degraded)
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.join("\n\n")
    |> Kernel.<>("\n")
  end

  # Mirrors `Valea.Mounts`'s own enabled/disabled/degraded split. Filtering
  # (rather than a single reduce) is fine here — `Mounts.list/1` is already
  # sorted by name, and each filter preserves relative order, so every
  # section stays alphabetically sorted without a separate sort step.
  defp categorize(mounts) do
    {degraded, rest} = Enum.split_with(mounts, &(&1.degraded != nil))
    {enabled, deactivated} = Enum.split_with(rest, & &1.enabled)
    {enabled, deactivated, degraded}
  end

  defp enabled_section([]), do: nil

  defp enabled_section(mounts) do
    Enum.map_join(mounts, "\n\n", &enabled_block/1)
  end

  # `mount.manifest` is guaranteed non-nil here: this clause only ever sees
  # mounts with `degraded: nil`, and `Valea.Mounts.list/1` only produces
  # `degraded: nil` when the manifest loaded successfully.
  defp enabled_block(%{manifest: %{name: name, description: description}, rel_root: rel_root}) do
    """
    ### #{name}
    #{description}
    path: #{rel_root}
    @#{rel_root}/AGENTS.md\
    """
  end

  defp deactivated_section([]), do: nil

  defp deactivated_section(mounts) do
    lines = Enum.map(mounts, &deactivated_line/1)
    Enum.join(["## Deactivated" | lines], "\n")
  end

  # Same non-nil manifest guarantee as `enabled_block/1` — `degraded: nil`.
  defp deactivated_line(%{manifest: %{name: name}, rel_root: rel_root}) do
    "- #{name} — #{rel_root} (disabled)"
  end

  defp needs_attention_section([]), do: nil

  defp needs_attention_section(mounts) do
    lines = Enum.map(mounts, &needs_attention_line/1)
    Enum.join(["## Needs attention" | lines], "\n")
  end

  # Degraded mounts may have `manifest: nil` (missing/invalid icm.yaml) —
  # render from `name`/`rel_root`/`degraded` only, never `mount.manifest`.
  defp needs_attention_line(%{name: name, rel_root: rel_root, degraded: reason}) do
    "- #{name} — #{rel_root}: #{reason}"
  end

  # -- atomic write ----------------------------------------------------------

  defp atomic_write!(path, content) do
    tmp = path <> ".tmp"
    File.write!(tmp, content)
    File.rename!(tmp, path)
  end
end
