defmodule ValeaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :valea

  socket "/socket", ValeaWeb.UserSocket,
    websocket: true,
    longpoll: false

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_valea_key",
    signing_salt: "WIAyBJ1y",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :valea,
    gzip: not code_reloading?,
    only: ValeaWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    # No Phoenix.Ecto.CheckRepoStatus: Valea.Repo only runs while a workspace is open.
    plug AshPhoenix.Plug.CheckCodegenStatus
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Transport backstop for image uploads (ValeaWeb.FilesController): the
    # controller's own explicit File.stat check enforces the real 10 MB
    # business cap, so this only needs headroom above that so the parser
    # doesn't reject a legitimate upload before the controller ever runs.
    length: 12_000_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # The packaged desktop window now loads the SPA same-origin from the sidecar
  # (http://localhost:4817), so these tauri:// origins no longer occur in
  # practice. Kept as a harmless safety net in case the window is ever loaded
  # from a custom protocol again; drop this plug if that never happens.
  plug Corsica,
    origins: ["tauri://localhost", "http://tauri.localhost", "https://tauri.localhost"],
    allow_headers: :all,
    allow_methods: :all

  plug ValeaWeb.Router
end
