defmodule Valea.Tasks do
  @moduledoc """
  The per-ICM task ledger — `tasks.json` at an ICM root, plus its archive at
  `.valea/task-archive.jsonl` (tasks+schedules spec §Data model, §Leniency
  contract, §Write discipline, §Archival).

  Tasks are **inert**: nothing here executes, schedules, or fires. The file
  is the truth, owned by the user and edited by agents with ordinary file
  tools; this module is Valea's disciplined way of touching the same file.

  ## Shape

      {
        "readme": "Task ledger for this ICM. …",
        "tasks": [
          {"id": "t-8f3a2c", "title": "…", "status": "open",
           "created_by": "user", "created_at": "…", "updated_at": "…",
           "done_at": null}
        ]
      }

  Ids are `t-` + 6 lowercase hex chars, generated by whoever creates the
  task; duplicates degrade softly (first occurrence wins for addressing, per
  spec, and `patch/4` patches exactly that one). Statuses are
  `open | in_progress | done | dropped`; `done`/`dropped` are the completed
  pair the archive is about. Timestamps are second-precision UTC ISO 8601.

  ## Leniency

  Reads never fail: `list/1` returns `%{status: :ok | :absent | :unreadable,
  tasks: [...]}` and the UI renders a calm note for the degenerate cases.
  Non-map members of the array are dropped from the *view* — and never from
  the *file*: every write here patches the document as read, so unknown
  entry fields, unknown top-level keys (`readme`, anything a newer app or a
  hand edit added) and even a stray `42` in the array survive Valea's writes.
  A `tasks` key that isn't an array is refused for mutation
  (`{:error, :unreadable}`) rather than clobbered.

  ## Write discipline

  Every mutation runs inside `Valea.Ledger.Writer.exec/1` (so Valea-side
  writes never interleave) and is an optimistic read-patch-write against the
  file's content hash, re-applied on conflict, bounded to 3 attempts before
  surfacing `{:error, :conflict}`. Reads deliberately skip the writer.
  Mutating APIs therefore need the Writer running (a `Valea.Workspace.
  Runtime` child); `list/1`, `archive_entries/1` and `snapshot_hash/1` do
  not.

  `patch/4` keeps `updated_at` current, and keeps `done_at` consistent with
  `status`: a patch that moves an entry *into* `done`/`dropped` stamps
  `done_at` (an existing stamp is kept, so re-marking done doesn't restart
  the auto-archive clock), and one that moves it *out* clears it. A
  `done_at` (or `updated_at`) supplied in the patch always wins, and a patch
  that doesn't touch `status` leaves `done_at` alone.

  Where the brief and the spec differ in wording, note the resolved
  behavior: an entry that has vanished by the time a patch is re-applied
  yields `{:error, :not_found}` (the spec calls it "a conflict surfaced to
  the UI"; the distinct atom is strictly more informative and nothing is
  written either way).

  ## Archival

  `archive_done/2` (UI "Clear done") and `sweep/2` (auto-archive of entries
  completed more than 14 days ago) both **append first, prune second**, in
  one writer turn:

    * Each archive line is `%{"archive_event", "archived_at",
      "snapshot_hash", "task"}`. **The snapshot hash is the identity** —
      lowercase hex SHA-256 over a key-sorted JSON encoding of the entry.
      The event id is a UUID and is provenance only: `id` and `updated_at`
      are optional-and-mutable and identify nothing.
    * A crash between append and prune leaves the entry in the ledger; the
      next sweep appends the same snapshot again under a fresh event id, so
      readers dedupe by `snapshot_hash` (`archive_entries/1` does). Corner,
      stated in the spec: genuinely distinct archivals of byte-identical
      content collapse on read — same fact, acceptable.
    * The prune is **snapshot-conditional**: an entry leaves the ledger only
      if its current content still hashes to what was archived. An entry
      edited or reopened in the window stays, and the archive line remains
      as history of the completed state it captured.
    * A partial trailing line (crash mid-append) is tolerated: readers drop
      it, and the next append starts on a fresh line rather than continuing
      it.

  ## Test seams

  Two documented opts exist only so tests can drive the windows that are
  otherwise the exclusive property of a foreign writer or a crash. They
  default to `nil` and no production caller passes them:

    * `:before_write` — `fun/0` or `fun/1` (the 1-based attempt number),
      called after the read and before the write of `create/3` and
      `patch/4`. Used to simulate an agent write landing mid-patch.
    * `:on_appended` — `fun/0`, called between the archive append and the
      snapshot-conditional prune.
  """

  alias Valea.Ledger.Canonical
  alias Valea.Ledger.JsonFile
  alias Valea.Ledger.Writer

  @list_key "tasks"
  @readme "Task ledger for this ICM. Managed by Valea and agents. Contract: .valea/briefing.md"
  @completed ~w(done dropped)
  @attempts 3
  @auto_archive_days 14

  @type status :: :ok | :absent | :unreadable
  @type archive_result ::
          {:ok, %{archived: non_neg_integer(), pruned: non_neg_integer()}}
          | {:error, :unreadable | :conflict}

  @doc "The ledger path for an ICM root."
  @spec tasks_path(String.t()) :: String.t()
  def tasks_path(icm_root), do: Path.join(icm_root, "tasks.json")

  @doc "The append-only archive path for an ICM root (inside Valea's `.valea/`)."
  @spec archive_path(String.t()) :: String.t()
  def archive_path(icm_root), do: Path.join([icm_root, ".valea", "task-archive.jsonl"])

  @doc """
  The ledger entries in file order, with the parse status alongside them.

  Entries are returned **as read** (unknown fields included); display
  leniency for individual fields belongs to the layer that renders them.
  """
  @spec list(String.t()) :: %{status: status(), tasks: [map()]}
  def list(icm_root) do
    case JsonFile.read(tasks_path(icm_root), @list_key) do
      {:ok, %{entries: entries}} -> %{status: :ok, tasks: entries}
      :absent -> %{status: :absent, tasks: []}
      {:error, :unreadable} -> %{status: :unreadable, tasks: []}
    end
  end

  @doc """
  Appends a task and returns the entry as written.

  `fields` are merged over Valea's defaults and win, so a caller (or an
  agent-facing RPC) can supply its own `id`, `status` or `created_by`; keys
  may be atoms or strings and are normalized to strings. An absent ledger is
  materialized with the spec skeleton (`readme` + empty `tasks`).
  """
  @spec create(String.t(), map(), keyword()) :: {:ok, map()} | {:error, :unreadable | :conflict}
  def create(icm_root, fields \\ %{}, opts \\ []) when is_map(fields) and is_list(opts) do
    Writer.exec(fn -> do_create(tasks_path(icm_root), stringify(fields), opts) end)
  end

  defp do_create(path, fields, opts) do
    with {:ok, %{doc: doc}} <- read_for_write(path),
         {:ok, list} <- writable_list(doc) do
      append_entry(path, new_entry(fields, list), opts, 1)
    end
  end

  defp append_entry(_path, _entry, _opts, attempt) when attempt > @attempts,
    do: {:error, :conflict}

  defp append_entry(path, entry, opts, attempt) do
    with {:ok, %{doc: doc, hash: expected}} <- read_for_write(path),
         {:ok, list} <- writable_list(doc) do
      run_hook(opts[:before_write], attempt)

      case JsonFile.write(path, Map.put(doc, @list_key, list ++ [entry]), expected) do
        :ok -> {:ok, entry}
        {:error, :conflict} -> append_entry(path, entry, opts, attempt + 1)
      end
    end
  end

  defp new_entry(fields, list) do
    now = now_iso()

    %{
      "id" => generate_id(taken_ids(list)),
      "status" => "open",
      "created_by" => "user",
      "created_at" => now,
      "updated_at" => now,
      "done_at" => nil
    }
    |> Map.merge(fields)
  end

  defp taken_ids(list) do
    for entry <- list, is_map(entry), is_binary(entry["id"]), into: MapSet.new(), do: entry["id"]
  end

  # 3 random bytes is plenty for a per-ICM ledger, and checking the ledger we
  # just read is free — so we check, a few times. Exhausting the tries just
  # takes the last candidate: a duplicate id degrades softly by spec (first
  # occurrence wins) rather than failing a task creation.
  defp generate_id(taken, tries \\ 8) do
    candidate = "t-" <> Base.encode16(:crypto.strong_rand_bytes(3), case: :lower)

    if tries > 1 and MapSet.member?(taken, candidate),
      do: generate_id(taken, tries - 1),
      else: candidate
  end

  @doc """
  Patches the first entry with `task_id`, returning the entry as written.

  `patch` is merged over the entry (unknown fields on both sides survive);
  see the moduledoc for the `updated_at`/`done_at` stamping rules. Retries
  the read-patch-write up to 3 times against a file changing underneath;
  `{:error, :not_found}` if the id isn't (or is no longer) there,
  `{:error, :conflict}` if contention persists — nothing is written in
  either case.
  """
  @spec patch(String.t(), String.t(), map(), keyword()) ::
          {:ok, map()} | {:error, :not_found | :conflict | :unreadable}
  def patch(icm_root, task_id, patch, opts \\ [])
      when is_binary(task_id) and is_map(patch) and is_list(opts) do
    Writer.exec(fn -> do_patch(tasks_path(icm_root), task_id, stringify(patch), opts, 1) end)
  end

  defp do_patch(_path, _task_id, _patch, _opts, attempt) when attempt > @attempts,
    do: {:error, :conflict}

  defp do_patch(path, task_id, patch, opts, attempt) do
    with {:ok, %{doc: doc, hash: expected}} <- read_for_write(path),
         {:ok, list} <- writable_list(doc),
         {:ok, entry, patched} <- apply_patch(list, task_id, patch) do
      run_hook(opts[:before_write], attempt)

      case JsonFile.write(path, Map.put(doc, @list_key, patched), expected) do
        :ok -> {:ok, entry}
        {:error, :conflict} -> do_patch(path, task_id, patch, opts, attempt + 1)
      end
    end
  end

  # Walks the raw list (junk members included, so they round-trip) and
  # patches the FIRST map whose id matches — the accumulator doubles as the
  # "already patched" flag, which is what makes first-occurrence-wins hold
  # for duplicate ids.
  defp apply_patch(list, task_id, patch) do
    {patched_list, updated} =
      Enum.map_reduce(list, nil, fn
        entry, nil when is_map(entry) ->
          if entry["id"] == task_id do
            patched = patch_entry(entry, patch)
            {patched, patched}
          else
            {entry, nil}
          end

        entry, already ->
          {entry, already}
      end)

    case updated do
      nil -> {:error, :not_found}
      entry -> {:ok, entry, patched_list}
    end
  end

  defp patch_entry(entry, patch) do
    now = now_iso()

    entry
    |> Map.merge(patch)
    |> Map.put("updated_at", Map.get(patch, "updated_at", now))
    |> stamp_done_at(patch, now)
  end

  defp stamp_done_at(entry, patch, now) do
    cond do
      Map.has_key?(patch, "done_at") -> entry
      not Map.has_key?(patch, "status") -> entry
      not completed?(entry) -> Map.put(entry, "done_at", nil)
      is_binary(entry["done_at"]) -> entry
      true -> Map.put(entry, "done_at", now)
    end
  end

  @doc """
  Archives every completed (`done`/`dropped`) entry — the UI's "Clear done".

  Append-first, prune-second and snapshot-conditional (see the moduledoc):
  `archived` counts the lines written to the archive, `pruned` the entries
  that actually left the ledger, which is lower when an entry was edited in
  the window. An absent ledger is a no-op.
  """
  @spec archive_done(String.t(), keyword()) :: archive_result()
  def archive_done(icm_root, opts \\ []) when is_list(opts) do
    Writer.exec(fn -> do_archive(icm_root, &completed?/1, opts) end)
  end

  @doc """
  Auto-archive sweep: completed entries whose `done_at` (falling back to
  `updated_at`) is more than #{@auto_archive_days} days before now.

  Same append-first/prune-second machinery as `archive_done/2`. `now:` (a
  `DateTime`, default `DateTime.utc_now/0`) injects the clock — the
  scheduler's daily sweep and tests use the same path. An entry with no
  parseable timestamp is never swept: unknown age is not old age.
  """
  @spec sweep(String.t(), keyword()) :: archive_result()
  def sweep(icm_root, opts \\ []) when is_list(opts) do
    now = now(opts)
    cutoff = DateTime.add(now, -@auto_archive_days * 86_400, :second)
    opts = Keyword.put(opts, :now, now)

    Writer.exec(fn -> do_archive(icm_root, &stale_completed?(&1, cutoff), opts) end)
  end

  defp do_archive(icm_root, eligible?, opts) do
    path = tasks_path(icm_root)

    with {:ok, %{doc: doc, entries: entries}} <- read_for_write(path),
         {:ok, _list} <- writable_list(doc) do
      case Enum.filter(entries, eligible?) do
        [] -> {:ok, %{archived: 0, pruned: 0}}
        eligible -> append_then_prune(icm_root, eligible, opts)
      end
    end
  end

  defp append_then_prune(icm_root, eligible, opts) do
    archived_at = opts |> now() |> DateTime.to_iso8601()

    lines =
      Enum.map(eligible, fn entry ->
        %{
          "archive_event" => Ecto.UUID.generate(),
          "archived_at" => archived_at,
          "snapshot_hash" => snapshot_hash(entry),
          "task" => entry
        }
      end)

    append_lines!(archive_path(icm_root), lines)
    run_hook(opts[:on_appended], nil)

    prune(tasks_path(icm_root), MapSet.new(lines, & &1["snapshot_hash"]), length(lines), 1)
  end

  # A failed prune leaves the archive lines in place on purpose: they are
  # idempotent on read (dedupe by snapshot hash), and the next sweep either
  # re-appends the same snapshot or finds the entry legitimately changed.
  defp prune(_path, _hashes, _archived, attempt) when attempt > @attempts,
    do: {:error, :conflict}

  defp prune(path, hashes, archived, attempt) do
    with {:ok, %{doc: doc, hash: expected}} <- read_for_write(path),
         {:ok, list} <- writable_list(doc),
         {kept, pruned} when pruned > 0 <- keep_unarchived(list, hashes),
         :ok <- JsonFile.write(path, Map.put(doc, @list_key, kept), expected) do
      {:ok, %{archived: archived, pruned: pruned}}
    else
      # Nothing left to prune: every archived snapshot has since been edited
      # away (or was already gone). The archive lines stand as history.
      {_kept, 0} -> {:ok, %{archived: archived, pruned: 0}}
      # Only `JsonFile.write/3` yields `:conflict` here — the reads above
      # can only fail as `:unreadable`.
      {:error, :conflict} -> prune(path, hashes, archived, attempt + 1)
      {:error, :unreadable} -> {:error, :unreadable}
    end
  end

  defp keep_unarchived(list, hashes) do
    kept = Enum.reject(list, &(is_map(&1) and MapSet.member?(hashes, snapshot_hash(&1))))
    {kept, length(list) - length(kept)}
  end

  # One JSON object per line. If the file doesn't end in a newline — a crash
  # mid-append — start on a fresh one rather than completing someone else's
  # torn line; readers drop the partial remains.
  defp append_lines!(path, lines) do
    File.mkdir_p!(Path.dirname(path))
    prefix = if unterminated?(path), do: "\n", else: ""
    data = Enum.map_join(lines, "", &(Jason.encode!(&1) <> "\n"))

    File.write!(path, prefix <> data, [:append])
  end

  defp unterminated?(path) do
    case File.stat(path) do
      {:ok, %File.Stat{size: size}} when size > 0 -> last_byte(path, size) != "\n"
      _absent_or_empty -> false
    end
  end

  defp last_byte(path, size) do
    {:ok, io} = File.open(path, [:read, :binary])

    try do
      case :file.pread(io, size - 1, 1) do
        {:ok, byte} -> byte
        _eof_or_error -> nil
      end
    after
      File.close(io)
    end
  end

  @doc """
  The archive as parsed lines, oldest first, **deduped by `snapshot_hash`**
  (first occurrence wins) — the read side of the crash-safe append.

  Junk and partial lines are dropped; a missing or unreadable archive is an
  empty list. Lines without a `snapshot_hash` are all kept: nothing
  identifies them, so nothing may collapse them.
  """
  @spec archive_entries(String.t()) :: [map()]
  def archive_entries(icm_root) do
    case File.read(archive_path(icm_root)) do
      {:ok, raw} -> raw |> String.split("\n") |> parse_lines() |> dedupe()
      {:error, _absent_or_unreadable} -> []
    end
  end

  defp parse_lines(lines) do
    Enum.flat_map(lines, fn line ->
      case Jason.decode(String.trim(line)) do
        {:ok, %{} = entry} -> [entry]
        _blank_partial_or_junk -> []
      end
    end)
  end

  defp dedupe(entries) do
    {kept, _seen} = Enum.reduce(entries, {[], MapSet.new()}, &dedupe_line/2)
    Enum.reverse(kept)
  end

  defp dedupe_line(entry, {kept, seen}) do
    hash = entry["snapshot_hash"]

    cond do
      not is_binary(hash) -> {[entry | kept], seen}
      MapSet.member?(seen, hash) -> {kept, seen}
      true -> {[entry | kept], MapSet.put(seen, hash)}
    end
  end

  @doc """
  The archive identity of a task snapshot: lowercase hex SHA-256 over a
  key-sorted JSON encoding (recursively — nested objects too), so the hash
  depends on the content and not on map iteration order.

  The canonical form lives in `Valea.Ledger.Canonical`, shared with the
  schedule execution fingerprint.
  """
  @spec snapshot_hash(map()) :: String.t()
  def snapshot_hash(task) when is_map(task), do: Canonical.hash(task)

  # -- shared read/write plumbing ---------------------------------------------

  # An absent ledger reads as the spec skeleton against an `:absent` hash, so
  # the first write materializes `readme` + `tasks` and still fails closed if
  # someone else created the file in the meantime.
  defp read_for_write(path) do
    case JsonFile.read(path, @list_key) do
      {:ok, read} ->
        {:ok, read}

      :absent ->
        {:ok, %{doc: %{"readme" => @readme, @list_key => []}, entries: [], hash: :absent}}

      {:error, :unreadable} ->
        {:error, :unreadable}
    end
  end

  # The RAW list, junk members included: dropping them from the display view
  # is leniency, dropping them from the file would be data loss. A `tasks`
  # key that isn't an array is not something to overwrite — the user gets the
  # same "fix by hand" note as for malformed JSON.
  defp writable_list(doc) do
    case Map.get(doc, @list_key, []) do
      list when is_list(list) -> {:ok, list}
      _wrong_typed -> {:error, :unreadable}
    end
  end

  defp completed?(entry), do: entry["status"] in @completed

  defp stale_completed?(entry, cutoff) do
    completed?(entry) and
      case completed_at(entry) do
        {:ok, at} -> DateTime.compare(at, cutoff) == :lt
        :error -> false
      end
  end

  defp completed_at(entry) do
    with :error <- parse_iso(entry["done_at"]), do: parse_iso(entry["updated_at"])
  end

  defp parse_iso(value) when is_binary(value) do
    case DateTime.from_iso8601(value) do
      {:ok, at, _offset} -> {:ok, at}
      {:error, _reason} -> :error
    end
  end

  defp parse_iso(_missing_or_wrong_typed), do: :error

  defp now(opts), do: opts |> Keyword.get(:now, DateTime.utc_now()) |> DateTime.truncate(:second)

  defp now_iso, do: [] |> now() |> DateTime.to_iso8601()

  defp stringify(fields), do: Map.new(fields, fn {key, value} -> {to_string(key), value} end)

  defp run_hook(nil, _arg), do: :ok
  defp run_hook(fun, arg) when is_function(fun, 1), do: fun.(arg)
  defp run_hook(fun, _arg) when is_function(fun, 0), do: fun.()
end
