defmodule Valea.Mail.SyncPass do
  @moduledoc """
  One mail sync pass (mail design spec, §Engine). Connects over a
  `Valea.Mail.Transport`, fully syncs the Review folder into landed
  `sources/mail/messages/<msg_id>.md` files, refreshes the INBOX awareness
  index (`sources/mail/inbox.md`), and returns the counts the Engine needs
  to broadcast `mail_sync_finished`.

  Pure of any GenServer state: `Valea.Mail.Engine` runs this in a monitored
  `Task` and owns the `syncing`/`auth_failed` status transitions. Everything
  the pass touches — the SQLite cache (`Valea.Mail.Store`) and the files
  under `sources/mail/` — is rebuildable per Principle 1, so a crashed pass
  reruns idempotently.

  ## Idempotency & the per-UID discipline

  The pass never trusts a bare high-water mark alone. For the Review folder
  it keeps a per-UID outcome (`synced | skipped_oversize | failed`) so a
  message that fails to land is *retried* on later passes (attempt-capped in
  `Store.outcomes/1`) rather than skipped forever, and an oversized one is
  not re-fetched. `UIDVALIDITY` is compared on every SELECT; a change wipes
  the folder's watermark + outcomes (`Store.clear_folder/1`) and forces a
  clean "ALL" re-fetch — but the landed **files** and `mail_messages` rows
  survive, so dedupe-by-Message-ID re-attaches them without rewriting a
  single byte.

  ## The `UID n:*` quirk

  `UID SEARCH UID n:*` returns the *last* message in the mailbox even when
  its UID is `< n` (RFC 3501: `n:*` is `min(n,last):max(n,last)`). Results
  are therefore filtered to `uid > high_water` here rather than trusting the
  server to have excluded already-seen UIDs.

  ## Error posture

  A folder-level failure (SELECT/SEARCH/META fetch) degrades that folder to
  an error string in the returned `errors` list without aborting the other
  folder or the LOGOUT. A single-message raise or per-UID transport error
  records `failed` for that UID (bumping its attempt count) and the pass
  continues — one bad message never wedges the pass. Only an auth failure at
  CONNECT aborts the whole pass (`{:error, :auth_failed}`), which the Engine
  turns into paused polling.
  """

  alias Valea.Mail.Message
  alias Valea.Mail.MessageFile
  alias Valea.Mail.Normalizer
  alias Valea.Mail.Store

  @inbox "INBOX"

  @inbox_header """
  <!-- Generated by Valea mail sync — regenerated every pass. Awareness index only; do not edit. -->

  """

  @type args :: %{
          root: String.t(),
          settings: Valea.Mail.Settings.t(),
          credential: (-> String.t()) | String.t(),
          transport: module()
        }

  @doc """
  Runs a full pass. `credential` is a zero-arity closure (the Engine holds
  the secret in RAM only) called exactly once, at the `transport.connect/3`
  boundary. Returns `{:ok, %{new_messages:, errors:}}` on a completed pass
  (even one with per-message errors), `{:error, :auth_failed}` verbatim from
  a failed login, or `{:error, term}` for any other connect failure.
  """
  @spec run(args()) ::
          {:ok, %{new_messages: non_neg_integer(), errors: [String.t()]}}
          | {:error, :auth_failed}
          | {:error, term()}
  def run(%{root: root, settings: settings, credential: credential, transport: transport}) do
    case transport.connect(settings.imap, resolve_credential(credential), []) do
      {:ok, conn} ->
        run_with_conn(%{conn: conn, root: root, settings: settings, transport: transport})

      {:error, :auth_failed} ->
        {:error, :auth_failed}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp resolve_credential(fun) when is_function(fun, 0), do: fun.()
  defp resolve_credential(secret) when is_binary(secret), do: secret

  defp run_with_conn(ctx) do
    {review_new, review_errors} = sync_review(ctx)
    inbox_errors = sync_inbox(ctx)
    safe_logout(ctx)
    {:ok, %{new_messages: review_new, errors: review_errors ++ inbox_errors}}
  rescue
    e ->
      safe_logout(ctx)
      {:error, e}
  end

  defp safe_logout(ctx) do
    ctx.transport.logout(ctx.conn)
    :ok
  rescue
    _ -> :ok
  catch
    _, _ -> :ok
  end

  # -- Review folder ----------------------------------------------------------

  defp sync_review(ctx) do
    folder = ctx.settings.folders.review

    case ctx.transport.select(ctx.conn, folder) do
      {:ok, %{uidvalidity: uidvalidity}} ->
        maybe_resync(folder, uidvalidity)
        do_sync_review(ctx, folder, uidvalidity)

      {:error, reason} ->
        {0, ["review select failed: #{inspect(reason)}"]}
    end
  end

  defp do_sync_review(ctx, folder, uidvalidity) do
    high_water = current_high_water(folder)

    case ctx.transport.uid_search(ctx.conn, search_criteria(high_water)) do
      {:ok, uids} ->
        candidates = select_candidates(uids, high_water, Store.outcomes(folder))
        {metas, meta_errors} = fetch_metas(ctx, candidates)
        {new_count, errors} = process_metas(ctx, folder, metas)
        update_sync_state(folder, uidvalidity, high_water, Enum.map(metas, & &1.uid))
        {new_count, meta_errors ++ errors}

      {:error, reason} ->
        Store.put_sync_state(folder, uidvalidity, high_water)
        {0, ["review search failed: #{inspect(reason)}"]}
    end
  end

  defp fetch_metas(_ctx, []), do: {[], []}

  defp fetch_metas(ctx, candidates) do
    case ctx.transport.uid_fetch_meta(ctx.conn, candidates) do
      {:ok, metas} -> {metas, []}
      {:error, reason} -> {[], ["review meta fetch failed: #{inspect(reason)}"]}
    end
  end

  defp process_metas(ctx, folder, metas) do
    {new, errors} =
      Enum.reduce(metas, {0, []}, fn meta, {n, errs} ->
        case process_one(ctx, folder, meta) do
          {:ok, :new} -> {n + 1, errs}
          {:ok, :dedupe} -> {n, errs}
          {:error, message} -> {n, [message | errs]}
        end
      end)

    {new, Enum.reverse(errors)}
  end

  # Per-message isolation: a raise anywhere in the land/side-effect stages
  # (attachment or message-file write, index upsert) records `failed` and is
  # collected rather than crashing the pass. Transport/`{:error, _}` per-UID
  # returns are handled (and recorded) inside process_normal/process_oversize.
  defp process_one(ctx, folder, %{size: size} = meta) do
    if size > ctx.settings.sync.max_message_bytes do
      process_oversize(ctx, folder, meta)
    else
      process_normal(ctx, folder, meta)
    end
  rescue
    e ->
      Store.record_outcome(folder, meta.uid, :failed)
      {:error, "uid #{meta.uid}: #{Exception.message(e)}"}
  catch
    kind, reason ->
      Store.record_outcome(folder, meta.uid, :failed)
      {:error, "uid #{meta.uid}: #{inspect({kind, reason})}"}
  end

  defp process_normal(ctx, folder, meta) do
    case ctx.transport.uid_fetch_full(ctx.conn, meta.uid) do
      {:ok, raw} ->
        {:ok, message} = Normalizer.normalize(raw)
        land_message(ctx, folder, meta, message, header_block(raw), :synced)

      {:error, reason} ->
        Store.record_outcome(folder, meta.uid, :failed)
        {:error, "uid #{meta.uid}: fetch failed: #{inspect(reason)}"}
    end
  end

  defp process_oversize(ctx, folder, meta) do
    case ctx.transport.uid_fetch_headers(ctx.conn, [meta.uid]) do
      {:ok, [%{header: header} | _]} ->
        message = oversize_message(header, meta.size, ctx.settings.sync.max_message_bytes)
        land_message(ctx, folder, meta, message, header, :skipped_oversize)

      {:ok, []} ->
        Store.record_outcome(folder, meta.uid, :failed)
        {:error, "uid #{meta.uid}: oversize header fetch returned nothing"}

      {:error, reason} ->
        Store.record_outcome(folder, meta.uid, :failed)
        {:error, "uid #{meta.uid}: oversize header fetch failed: #{inspect(reason)}"}
    end
  end

  defp oversize_message(header, size, cap) do
    parsed = Normalizer.parse_headers(header)

    %Message{
      message_id: parsed.message_id,
      from: parsed.from,
      to: [],
      subject: parsed.subject,
      date: parsed.date,
      body_text: "",
      attachments: [],
      notes: %{
        truncation_note:
          "message body omitted: #{size} bytes exceeds the #{cap}-byte sync cap; headers only"
      }
    }
  end

  # Dedupe on the full Message-ID via the index, then land: write attachments,
  # render + atomically write the message file, upsert the index row, record
  # the outcome, audit, and broadcast. A hit re-uses the existing file (no
  # write) and only records the outcome so the UID stops being a candidate.
  defp land_message(ctx, folder, meta, message, header_source, outcome) do
    case dedupe_lookup(message) do
      {:ok, existing} ->
        Store.record_outcome(folder, meta.uid, outcome, existing.msg_id)
        {:ok, :dedupe}

      :new ->
        msg_id = msg_id_for_path(ctx.root, message, header_source)
        attachments = write_attachments(ctx.root, msg_id, message.attachments)
        rel_path = write_message_file(ctx.root, msg_id, meta.uid, message, attachments)

        Store.upsert_message(%{
          msg_id: msg_id,
          message_id: message.message_id,
          path: rel_path,
          from: message.from,
          subject: message.subject,
          date: message.date,
          status: "review",
          has_attachments: attachments != [],
          uid: meta.uid
        })

        Store.record_outcome(folder, meta.uid, outcome, msg_id)

        if outcome == :synced,
          do: audit("mail_message_synced", %{"msg_id" => msg_id, "uid" => meta.uid})

        broadcast({:mail_message_upserted, %{path: rel_path}})
        {:ok, :new}
    end
  end

  defp dedupe_lookup(%Message{message_id: nil}), do: :new

  defp dedupe_lookup(%Message{message_id: message_id}) do
    case Store.message_by_message_id(message_id) do
      {:ok, existing} -> {:ok, existing}
      {:error, :not_found} -> :new
    end
  end

  # -- message file & msg_id --------------------------------------------------

  defp write_message_file(root, msg_id, uid, message, attachments) do
    bytes =
      MessageFile.render(message, %{
        msg_id: msg_id,
        uid: uid,
        status: "review",
        source: "imap",
        attachments: attachments
      })

    rel_path = message_rel_path(msg_id)
    abs_path = Path.join(root, rel_path)
    File.mkdir_p!(Path.dirname(abs_path))
    atomic_write!(abs_path, bytes)
    rel_path
  end

  defp message_rel_path(msg_id), do: Path.join(["sources", "mail", "messages", "#{msg_id}.md"])

  # `MessageFile.msg_id/2` yields the default 8-hex stem. On a path collision
  # with a *different* Message-ID the hash extends to 16 then 64 chars (spec
  # §Normalized message file); a collision with the *same* Message-ID reuses
  # the id (the deterministic re-land after a wiped DB).
  defp msg_id_for_path(root, message, header_source) do
    full = full_hash(message, header_source)
    prefix = id_prefix(message, header_source, full)

    Enum.find_value([8, 16, 64], fn n ->
      candidate = prefix <> String.slice(full, 0, n)
      path = Path.join(root, message_rel_path(candidate))

      cond do
        not File.exists?(path) -> candidate
        same_message_file?(path, message.message_id) -> candidate
        true -> nil
      end
    end) || prefix <> full
  end

  defp id_prefix(message, header_source, full) do
    base = MessageFile.msg_id(message, header_source)
    String.replace_suffix(base, String.slice(full, 0, 8), "")
  end

  defp full_hash(%Message{message_id: message_id}, header_source) do
    source = if blank?(message_id), do: header_source, else: message_id
    :sha256 |> :crypto.hash(source) |> Base.encode16(case: :lower)
  end

  defp same_message_file?(path, message_id) do
    with {:ok, bytes} <- File.read(path),
         {:ok, %{frontmatter: frontmatter}} <- MessageFile.parse(bytes) do
      Map.get(frontmatter, "message_id") == message_id
    else
      _ -> false
    end
  end

  # -- attachments ------------------------------------------------------------

  defp write_attachments(_root, _msg_id, []), do: []

  defp write_attachments(root, msg_id, attachments) do
    dir = Path.join([root, "sources", "mail", "attachments", msg_id])
    File.mkdir_p!(dir)

    {landed, _used} =
      Enum.reduce(attachments, {[], MapSet.new()}, fn attachment, {acc, used} ->
        filename = dedupe_filename(MessageFile.sanitize_filename(attachment.filename), used)
        atomic_write!(Path.join(dir, filename), attachment.content)

        entry = %{
          filename: filename,
          path: Path.join(["sources", "mail", "attachments", msg_id, filename]),
          bytes: byte_size(attachment.content)
        }

        {[entry | acc], MapSet.put(used, filename)}
      end)

    Enum.reverse(landed)
  end

  defp dedupe_filename(name, used) do
    if MapSet.member?(used, name) do
      {base, ext} = split_ext(name)

      Enum.find_value(Stream.iterate(1, &(&1 + 1)), fn i ->
        candidate = "#{base}-#{i}#{ext}"
        unless MapSet.member?(used, candidate), do: candidate
      end)
    else
      name
    end
  end

  defp split_ext(name) do
    ext = Path.extname(name)
    {Path.basename(name, ext), ext}
  end

  # -- INBOX ------------------------------------------------------------------

  defp sync_inbox(ctx) do
    case ctx.transport.select(ctx.conn, @inbox) do
      {:ok, %{uidvalidity: uidvalidity}} ->
        maybe_resync(@inbox, uidvalidity)
        do_sync_inbox(ctx, uidvalidity)

      {:error, reason} ->
        ["inbox select failed: #{inspect(reason)}"]
    end
  end

  defp do_sync_inbox(ctx, uidvalidity) do
    high_water = current_high_water(@inbox)

    case ctx.transport.uid_search(ctx.conn, search_criteria(high_water)) do
      {:ok, uids} ->
        new_uids = uids |> Enum.filter(&above?(&1, high_water)) |> Enum.sort()
        errors = fetch_and_store_headers(ctx, new_uids)
        Store.prune_inbox_headers(ctx.settings.sync.inbox_index_limit)
        regenerate_inbox_md(ctx.root)
        update_sync_state(@inbox, uidvalidity, high_water, new_uids)
        errors

      {:error, reason} ->
        Store.put_sync_state(@inbox, uidvalidity, high_water)
        ["inbox search failed: #{inspect(reason)}"]
    end
  end

  defp fetch_and_store_headers(_ctx, []), do: []

  defp fetch_and_store_headers(ctx, uids) do
    case ctx.transport.uid_fetch_headers(ctx.conn, uids) do
      {:ok, headers} ->
        Enum.each(headers, fn %{uid: uid, header: header} ->
          parsed = Normalizer.parse_headers(header)

          Store.put_inbox_header(%{
            uid: uid,
            from_text: from_text(parsed.from),
            subject: parsed.subject,
            date: parsed.date
          })
        end)

        []

      {:error, reason} ->
        ["inbox header fetch failed: #{inspect(reason)}"]
    end
  end

  defp from_text(%{name: name, email: email}) do
    cond do
      present?(name) and present?(email) -> "#{name} <#{email}>"
      present?(name) -> name
      present?(email) -> email
      true -> ""
    end
  end

  defp regenerate_inbox_md(root) do
    rel_path = Path.join(["sources", "mail", "inbox.md"])
    abs_path = Path.join(root, rel_path)
    File.mkdir_p!(Path.dirname(abs_path))
    atomic_write!(abs_path, render_inbox_md(Store.inbox_headers()))
  end

  defp render_inbox_md(headers) do
    rows =
      Enum.map_join(headers, "", fn h ->
        "| #{md_cell(h.date)} | #{md_cell(h.from_text)} | #{md_cell(h.subject)} |\n"
      end)

    @inbox_header <> "| date | from | subject |\n| --- | --- | --- |\n" <> rows
  end

  defp md_cell(nil), do: ""

  defp md_cell(value) do
    value
    |> to_string()
    |> String.replace("\\", "\\\\")
    |> String.replace("|", "\\|")
    |> String.replace(["\r\n", "\n", "\r"], " ")
  end

  # -- shared sync-state helpers ----------------------------------------------

  # A UIDVALIDITY change means every UID under the old value is meaningless:
  # wipe the folder's watermark + outcomes so the next SEARCH is a clean
  # "ALL" and every message is treated as unseen (files/index survive, so
  # Message-ID dedupe re-attaches them). No prior state -> nothing to do.
  defp maybe_resync(folder, uidvalidity) do
    case Store.get_sync_state(folder) do
      {:ok, %{uidvalidity: prev}} when is_integer(prev) and prev != uidvalidity ->
        Store.clear_folder(folder)

        audit("mail_folder_resync", %{
          "folder" => folder,
          "old_uidvalidity" => prev,
          "new_uidvalidity" => uidvalidity
        })

      _ ->
        :ok
    end
  end

  defp current_high_water(folder) do
    case Store.get_sync_state(folder) do
      {:ok, %{high_water_uid: high_water}} -> high_water
      {:error, :not_found} -> nil
    end
  end

  defp update_sync_state(folder, uidvalidity, old_high_water, seen_uids) do
    high_water =
      case Enum.reject([old_high_water | seen_uids], &is_nil/1) do
        [] -> nil
        list -> Enum.max(list)
      end

    Store.put_sync_state(folder, uidvalidity, high_water)
  end

  defp select_candidates(uids, high_water, outcomes) do
    fresh =
      uids
      |> Enum.filter(&above?(&1, high_water))
      |> Enum.reject(
        &(MapSet.member?(outcomes.synced, &1) or MapSet.member?(outcomes.skipped, &1))
      )

    (fresh ++ outcomes.retryable) |> Enum.uniq() |> Enum.sort()
  end

  defp search_criteria(nil), do: "ALL"
  defp search_criteria(high_water), do: "UID #{high_water + 1}:*"

  defp above?(_uid, nil), do: true
  defp above?(uid, high_water), do: uid > high_water

  # -- misc -------------------------------------------------------------------

  defp header_block(raw) do
    case :binary.split(raw, ["\r\n\r\n", "\n\n"]) do
      [headers, _body] -> headers
      [only] -> only
    end
  end

  defp atomic_write!(abs_path, bytes) do
    tmp = abs_path <> ".tmp"
    File.write!(tmp, bytes)
    File.rename!(tmp, abs_path)
  end

  defp blank?(nil), do: true
  defp blank?(string), do: String.trim(string) == ""

  defp present?(value), do: is_binary(value) and String.trim(value) != ""

  defp broadcast(event), do: Phoenix.PubSub.broadcast(Valea.PubSub, "mail", event)

  defp audit(type, fields) do
    if Process.whereis(Valea.Audit), do: Valea.Audit.append(type, fields)
    :ok
  end
end
